// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjAD_6Min8aJfOJ0rG0rndgcZodvKBYYA',
    appId: '1:219800021678:web:059ad656664e1855c55b3f',
    messagingSenderId: '219800021678',
    projectId: 'autofixlk-72a01',
    authDomain: 'autofixlk-72a01.firebaseapp.com',
    storageBucket: 'autofixlk-72a01.firebasestorage.app',
    measurementId: 'G-19039RXQ2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeojExguVzX0xDgFavAKrnGZs7QTFXL6o',
    appId: '1:219800021678:android:be65c0e44f38bcaac55b3f',
    messagingSenderId: '219800021678',
    projectId: 'autofixlk-72a01',
    storageBucket: 'autofixlk-72a01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtVJ4UN9210ZRKDhXnfkCT6qBi0YTTHcY',
    appId: '1:219800021678:ios:13358c1d6c746ee6c55b3f',
    messagingSenderId: '219800021678',
    projectId: 'autofixlk-72a01',
    storageBucket: 'autofixlk-72a01.firebasestorage.app',
    iosBundleId: 'com.autofixlk.app',
  );
}
